import type { Metadata } from "next";
import { ReduxProvider } from "@/components/ReduxProvider";
import './globals.css';
import ProtectedRoutes from "@/components/ProtectedRoutes";

export const metadata: Metadata = {
  title: "Futsal Booking System",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ProtectedRoutes>
            {children}
          </ProtectedRoutes>
        </ReduxProvider>
      </body>
    </html>
  );
}
