import type { Metadata } from "next";
import { ReduxProvider } from "@/components/ReduxProvider";
import './globals.css';
import RouteTest from "@/components/hooks/RouteTest";

export const metadata: Metadata = {
  title: "Futsal Booking System",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
