"use client"

// import type { Metadata } from "next";
import { ReduxProvider } from "@/components/ReduxProvider";
import ProtectedRoutes from "@/components/ProtectedRoutes";
import { Inter } from "next/font/google";
// import AppInitializer from "@/components/AppInitializer";
import './globals.css';
import { SessionProvider } from "next-auth/react";

// export const metadata: Metadata = {
//   title: "Futsal Booking System",
//   description: "Generated by create next app",
// };
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <ProtectedRoutes>
            <div className="max-w-[120rem] mx-auto">
              {/* <AppInitializer /> */}
              <SessionProvider>
                {children}
              </SessionProvider>
            </div>
          </ProtectedRoutes>
        </ReduxProvider>
      </body>
    </html>
  );
}
