import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/common/Navbar";


export const metadata: Metadata = {
   title: "Futsal Booking System",
   description: "Generated by create next app",

};

export default function UserLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body>
            {/* <RouteTest /> */}
            <Navbar />
            {children}
         </body>
      </html>
   );
}
